<a href="https://colab.research.google.com/github/Shiva-panda/essential-thing/blob/main/numpy_advance_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.zeros(5) #Return a new array of given shape and type, filled with zeros.

In [3]:
a

array([0., 0., 0., 0., 0.])

In [4]:
a.ndim

1

In [5]:
b = np.zeros((3, 4))

In [6]:
b.ndim

2

In [7]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.array([[2, 2, 2], [2, 2, 2]])

array([[2, 2, 2],
       [2, 2, 2]])

In [9]:
arr = np.zeros((3, 4))

In [10]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
arr.ndim

2

In [12]:
#3 dimensional array
np.zeros(1)

array([0.])

In [13]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
arr = np.zeros((3, 4))
arr.ndim

2

In [15]:
arr = np.zeros((1, 3, 4))
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [16]:
arr.ndim

3

In [17]:
arr = np.zeros((1, 1, 3, 4))
arr

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [18]:
arr.ndim

4

In [19]:
arr = np.zeros((1, 1, 1, 3, 4))
arr

array([[[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]]])

In [20]:
arr.ndim

5

In [21]:
arr

array([[[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]]])

In [22]:
arr = np.ones((3, 4))

In [23]:
arr.ndim

2

In [24]:
arr.shape

(3, 4)

In [25]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
arr + 5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [27]:
a = arr * 5

In [28]:
a

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [29]:
a - 1

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [30]:
np.eye(3) #Return a 2-D array with ones on the diagonal and zeros elsewhere.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.eye(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [32]:
np.empty((3, 4)) #Return a new array of given shape and type, without initializing entries

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [33]:
#optional >> random module

import random
random.choice((1, 2, 3, 4, 5))

2

In [34]:
random.choice('Ajay')

'A'

In [35]:
random.randrange(1, 10)

9

In [36]:
random.random() # a random no is generated between 0(included) and 1 (excluded)

0.9900016018575014

In [37]:
lis = [1, 2, 3, 4, 5]
lis

[1, 2, 3, 4, 5]

In [38]:
random.shuffle(lis)

In [39]:
lis

[2, 4, 5, 1, 3]

In [40]:
random.uniform(7, 14)

7.004644160621656

In [41]:

#random numbers related concepts in numpy
np.array([])

array([], dtype=float64)

In [42]:
np.random.random_sample()

0.8981233616172546

In [43]:
np.random.random_sample((5, ))

array([0.97333451, 0.75385453, 0.43717674, 0.55741895, 0.06819999])

In [44]:
np.random.rand(1)

array([0.20000532])

In [45]:
np.random.rand(2, 3)

array([[0.80228567, 0.30749142, 0.84951427],
       [0.82567589, 0.11603035, 0.69703591]])

In [46]:
np.random.randn(2,3)

array([[ 1.33152665,  1.49618106,  1.62187935],
       [-0.88766077,  1.28053394,  0.24352704]])

In [47]:
arr = np.random.randint(1, 5, size= (3, 4))

In [48]:
arr.ndim

2

In [49]:
arr.shape

(3, 4)

In [50]:
arr.size

12

In [51]:
arr

array([[1, 2, 1, 1],
       [2, 1, 1, 1],
       [2, 2, 4, 2]])

In [52]:
#reshaping the array

arr1 = arr.reshape(2, 6)

In [53]:
arr1.shape

(2, 6)

In [54]:
arr1.size

12

In [55]:
arr

array([[1, 2, 1, 1],
       [2, 1, 1, 1],
       [2, 2, 4, 2]])

In [56]:
arr.size

12

In [57]:
#array size will not change, always resape parameter should be multiplication of original array size

In [58]:
arr

array([[1, 2, 1, 1],
       [2, 1, 1, 1],
       [2, 2, 4, 2]])

In [59]:
arr.size

12

In [60]:
arr.reshape(12,1)

array([[1],
       [2],
       [1],
       [1],
       [2],
       [1],
       [1],
       [1],
       [2],
       [2],
       [4],
       [2]])

In [61]:
arr.reshape(1, 12)

array([[1, 2, 1, 1, 2, 1, 1, 1, 2, 2, 4, 2]])

In [62]:
arr.reshape(2,2, 3)

array([[[1, 2, 1],
        [1, 2, 1]],

       [[1, 1, 2],
        [2, 4, 2]]])

In [63]:
arr.reshape(3,4)

array([[1, 2, 1, 1],
       [2, 1, 1, 1],
       [2, 2, 4, 2]])

In [64]:
#case when you dont know in reshape what should be the column count

arr.reshape(4, -1)

array([[1, 2, 1],
       [1, 2, 1],
       [1, 1, 2],
       [2, 4, 2]])

In [65]:
arr.reshape(2, -1)

array([[1, 2, 1, 1, 2, 1],
       [1, 1, 2, 2, 4, 2]])

In [66]:
arr.reshape(2, -100)

array([[1, 2, 1, 1, 2, 1],
       [1, 1, 2, 2, 4, 2]])

In [67]:
arr1 = arr.reshape(-1, 3)#you know column count but no row count

In [68]:
arr1.size

12

In [69]:
arr.reshape(12, 1)

array([[1],
       [2],
       [1],
       [1],
       [2],
       [1],
       [1],
       [1],
       [2],
       [2],
       [4],
       [2]])

In [70]:
arr.reshape(12, 1).base #to see the original array

array([[1, 2, 1, 1],
       [2, 1, 1, 1],
       [2, 2, 4, 2]])

In [71]:
arr.reshape(2, 2, 3)

array([[[1, 2, 1],
        [1, 2, 1]],

       [[1, 1, 2],
        [2, 4, 2]]])

In [72]:
arr.reshape(1, 2, 2, 3)

array([[[[1, 2, 1],
         [1, 2, 1]],

        [[1, 1, 2],
         [2, 4, 2]]]])

In [73]:
arr.reshape(1, 2, 2, 3).ndim

4

In [74]:
arr.reshape(4, 3, 1) #3 rows 1 column repeated 4 times in the third dimension

array([[[1],
        [2],
        [1]],

       [[1],
        [2],
        [1]],

       [[1],
        [1],
        [2]],

       [[2],
        [4],
        [2]]])

In [75]:
#conditions on array

arr1 = np.random.randint(1, 10, (5,6))

In [76]:
arr1

array([[8, 9, 7, 9, 7, 6],
       [4, 3, 8, 6, 4, 6],
       [1, 4, 8, 6, 4, 9],
       [5, 6, 5, 6, 7, 7],
       [1, 1, 1, 2, 1, 2]])

In [77]:
arr1.shape

(5, 6)

In [78]:
arr1.ndim

2

In [79]:
arr1.size

30

In [80]:
arr1 > 3

array([[ True,  True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True,  True],
       [False,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [False, False, False, False, False, False]])

In [81]:
arr1[arr1> 3]

array([8, 9, 7, 9, 7, 6, 4, 8, 6, 4, 6, 4, 8, 6, 4, 9, 5, 6, 5, 6, 7, 7])

In [82]:
arr1[arr1 < 3]

array([1, 1, 1, 1, 2, 1, 2])

In [83]:
arr1

array([[8, 9, 7, 9, 7, 6],
       [4, 3, 8, 6, 4, 6],
       [1, 4, 8, 6, 4, 9],
       [5, 6, 5, 6, 7, 7],
       [1, 1, 1, 2, 1, 2]])

In [84]:
#To access elements in the array
arr1[0]

array([8, 9, 7, 9, 7, 6])

In [85]:
arr1[1]

array([4, 3, 8, 6, 4, 6])

In [86]:
arr1[1][0]

np.int64(4)

In [87]:
arr1

array([[8, 9, 7, 9, 7, 6],
       [4, 3, 8, 6, 4, 6],
       [1, 4, 8, 6, 4, 9],
       [5, 6, 5, 6, 7, 7],
       [1, 1, 1, 2, 1, 2]])

In [88]:
arr1[0:3] #oth row, 1st row and 2nd row

array([[8, 9, 7, 9, 7, 6],
       [4, 3, 8, 6, 4, 6],
       [1, 4, 8, 6, 4, 9]])

In [89]:
arr1[0:3, [0, 2]] #0to2nd row and 0th and 2nd column

array([[8, 7],
       [4, 8],
       [1, 8]])

In [90]:
#slicing on both rows and column

In [91]:
arr1

array([[8, 9, 7, 9, 7, 6],
       [4, 3, 8, 6, 4, 6],
       [1, 4, 8, 6, 4, 9],
       [5, 6, 5, 6, 7, 7],
       [1, 1, 1, 2, 1, 2]])

In [92]:
arr1[0:3, 1:3]

array([[9, 7],
       [3, 8],
       [4, 8]])

In [93]:
arr1[0:2, [0,1]]

array([[8, 9],
       [4, 3]])

In [94]:
arr1[0, [1, 3]]

array([9, 9])

In [95]:
arr1[2:4, [0, 3]]

array([[1, 6],
       [5, 6]])

In [96]:
arr1[2:5]

array([[1, 4, 8, 6, 4, 9],
       [5, 6, 5, 6, 7, 7],
       [1, 1, 1, 2, 1, 2]])

In [97]:
arr1[2:5, 0:2]

array([[1, 4],
       [5, 6],
       [1, 1]])

In [98]:
#mathematical operation on two arrays
arr1 = np.random.randint(1, 3, (3, 3))
arr2 = np.random.randint(1, 3, (3, 3))

In [99]:
arr1

array([[1, 1, 2],
       [1, 1, 2],
       [1, 1, 1]])

In [100]:
arr2

array([[1, 1, 1],
       [2, 2, 1],
       [2, 2, 2]])

In [101]:
arr1+arr2 #indewise elment addition

array([[2, 2, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [102]:
arr1-arr2 #indexwise element substraction

array([[ 0,  0,  1],
       [-1, -1,  1],
       [-1, -1, -1]])

In [103]:
arr1 * arr2 #index wise multiplication

array([[1, 1, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [104]:
arr1, arr2

(array([[1, 1, 2],
        [1, 1, 2],
        [1, 1, 1]]),
 array([[1, 1, 1],
        [2, 2, 1],
        [2, 2, 2]]))

In [105]:
arr1 / arr2 #index wise divison

array([[1. , 1. , 2. ],
       [0.5, 0.5, 2. ],
       [0.5, 0.5, 0.5]])

In [106]:
#4/0

In [107]:
arr1 / 0 #in python zero divion error will come, but in numpy no error

/tmp/ipython-input-1550714841.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1 / 0 #in python zero divion error will come, but in numpy no error


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [108]:
#matric multiplication>> different from index wise multiplication

arr1 @ arr2 #1st way to do matrix multiplication

array([[7, 7, 6],
       [7, 7, 6],
       [5, 5, 4]])

In [109]:
np.dot(arr1, arr2) #ndst way to do matrix multiplication

array([[7, 7, 6],
       [7, 7, 6],
       [5, 5, 4]])

In [110]:
arr = np.zeros((3, 4))

In [111]:
#broadcasting
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [112]:
arr + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [113]:
arr-5

array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.]])

In [114]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [115]:
a = np.array([1, 2, 3, 4])

In [116]:
a

array([1, 2, 3, 4])

In [117]:
a.ndim

1

In [118]:
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [119]:
a = np.array([[1, 2, 3, 4]])

In [120]:
a

array([[1, 2, 3, 4]])

In [121]:
#Transpose
a.T

array([[1],
       [2],
       [3],
       [4]])

In [122]:
arr1

array([[1, 1, 2],
       [1, 1, 2],
       [1, 1, 1]])

In [123]:
arr1.T

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 1]])

In [125]:
'''from google.colab import drive
drive.mount('/content/drive')'''

"from google.colab import drive\ndrive.mount('/content/drive')"

In [126]:
'''import nbformat

# ✅ Corrected paths (include MyDrive)
first_notebook = "/content/drive/sample_data/Data Toolkit/Numpy basics.ipynb"
second_notebook = "/content/drive/sample_data/Data Toolkit/numpy_advance-1ipynb"
merged_notebook = "/content/drive/sample_data/Data toolkit/Merged_Notebook.ipynb"

nb1 = nbformat.read(first_notebook, as_version=4)
nb2 = nbformat.read(second_notebook, as_version=4)

nb1.cells.extend(nb2.cells)
nbformat.write(nb1, merged_notebook)

print("✅ Merged notebook saved at:", merged_notebook)
'''


'import nbformat\n\n# ✅ Corrected paths (include MyDrive)\nfirst_notebook = "/content/drive/sample_data/Data Toolkit/Numpy basics.ipynb"\nsecond_notebook = "/content/drive/sample_data/Data Toolkit/numpy_advance-1ipynb"\nmerged_notebook = "/content/drive/sample_data/Data toolkit/Merged_Notebook.ipynb"\n\nnb1 = nbformat.read(first_notebook, as_version=4)\nnb2 = nbformat.read(second_notebook, as_version=4)\n\nnb1.cells.extend(nb2.cells)\nnbformat.write(nb1, merged_notebook)\n\nprint("✅ Merged notebook saved at:", merged_notebook)\n'

In [127]:
!ls

sample_data
